language: csharp
solution: PlanningPoker.Client.sln
install:
  - nuget restore solution-name.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./PlanningPoker.Client.Tests/bin/Release/PlanningPoker.Client.Tests.dll
