version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./PlanningPoker.Client/PlanningPoker.Client/PlanningPoker.Client.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netversion/publish
  - cmd: dotnet publish ./PlanningPoker.Client/PlanningPoker.Client/PlanningPoker.Client.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\PlanningPoker.Client\bin\Debug\netstandard2.0\publish'
   name: WebSite
   type: dll
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./PlanningPoker.Client/PlanningPoker.Client.Tests/PlanningPoker.Client.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  # - cmd: ../PlanningPoker.Client.Tests
  - cmd: dotnet test ./PlanningPoker.Client/PlanningPoker.Client.Tests/PlanningPoker.Client.Tests.csproj
on_finish :
  # any cleanup in here
deploy: off