name: BuildTest

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "*" ]
permissions:
  contents: read
  actions: read
  checks: write
jobs:    
  build:
    defaults:
      run:
        working-directory: ./PlanningPoker.Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
  
  unit-test:
    defaults:
      run:
        working-directory: ./PlanningPoker.Client
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Unit Tests
        run: dotnet test --verbosity normal --filter FullyQualifiedName!~integration --logger "trx;LogFileName=unit-test-results.trx"
      - name: Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: "**/unit-test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
          
  integration-test:
    defaults:
      run:
        working-directory: ./PlanningPoker.Client
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Integration Tests
        env:
            API_KEY: ${{ secrets.apiKey }}
        run: dotnet test --verbosity normal --filter FullyQualifiedName~integration --logger "trx;LogFileName=integration-test-results.trx" --environment PokerConnectionSettings__ApiKey=$API_KEY
      - name: Integration Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Test Results
          path: "**/integration-test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true